import move_limit, floor

def script():
    move_limit.lim3()
    print('문을 열고 나가려던 찰나, 누가 문을 세게 열었다.')
    move_limit.lim3()
    print('문의 접합부가 내는 끼이익, 하는 소리에 고개를 들면, 죽기 직전에 봤던 남자가 서있다.')
    move_limit.lim3()
    print('남자는 날 보고 표정을 환히 밝혔다가, 순식간에 일그러트렸다.')
    move_limit.lim3()
    print('아아.. 또 실패작이야.. 또.... 또 실패...... ')
    move_limit.lim3()
    print('알 수 없는 말을 중얼거리며 내 양 팔목을 으스러트리기라도 하려는 듯 꽉 쥐었다.')
    move_limit.lim3()
    print(f'[*] 손을 뿌리칠까?')
    print(f'【1】 뿌리치자. 기분 나쁘다.')
    print(f'【2】 무슨 사정인지 모르니 가만히 있는다.')
    num = input('선택>> ')
    num = int(num)
    if num == 1:
        print('손을 사납게 쳐냈다. 남자는 고개를 번쩍 들어 날 쳐다봤다.')
        move_limit.lim3()
        print('번들거리는 눈, 충혈된 탓에 빨개진 흰자... 이사람, 확실히 제정신이 아니다.')
        move_limit.lim3()
    else:
        print('남자는 제가 내 손을 쥐고 있었다는 것도 몰랐는지 화들짝 놀라며 멀어졌다.')
        move_limit.lim3()
        print("이미 그의 시야에는 내가 없다. '다가'와 '그들'이란 말만 미친 사람처럼 반복하고 있다.")
        move_limit.lim3()
    print('남자는 힘없이 방향을 돌려 비틀비틀 걸어갔다. 시간이 없어, 시간이, 그들이 날...')
    move_limit.lim3()

    print(f'[*] 무슨 일인지 물어볼까?')
    print(f'【1】 물어보자.')
    print(f'【2】 그냥 지나가자.')
    num = input('선택>> ')
    num = int(num)
    if num == 1:
        print('무슨 일? 하, 하하.... 그래, 학생... 젊어 보이는데 미안하게 됐어... 하지만, 나도 사정이 있어요.')
        move_limit.lim3()
        print('나는, 나는,... 내 연인을 살리려고 했어요.... 그들이 시키는대로 했단 말이야......')
        move_limit.lim3()
        print('그들이 시키는대로 사람을 죽이고, 응? 서재에 틀어박혀서 열심히 연구하고, 주문도 열심히 외웠어요. 그런데 이게 뭐야...')
        move_limit.lim3()
        print('처음엔 괜찮았어요. 죽었던 게 언제냐는 듯 다들 멀쩡히 돌아다녔고..., 그런데, 그, 그런데.')
        move_limit.lim3()
        print('하루도 지나지 않아서 괴물이... 되잖아요. 응? 지금 학생 몸에서 나는 썩은내 안 맡아져요?')
        move_limit.lim3()
        print('아, 아아아! 아아아아아!!! 다가, 다가! 왜 날 두고 간 거야!! 네가 없는 세상은 끔찍하고 역겨워!')
        move_limit.lim3()
        print('남자는 상체를 뒤로 젖혀선 괴성을 질렀다. 얼마 지나지 않아 입을 딱 다물고, 자세를 바로했다.')
        move_limit.lim3()
        print('...그래, 다가, 적어도 네가 외롭진 않겠구나.')
        move_limit.lim3()
        print('난, 죗값을 받겠지요. 그러니 날 너무 미워하진 마세요... 나도 불쌍한 사람이니까...')
        move_limit.lim3()
        print('남자는 덜덜 떨며 날 문 밖으로 밀어냈다.')
        move_limit.lim3()
    else:
        print('남자를 무시하고 지나쳐 나왔다. 불쾌하긴...')
        move_limit.lim3()
    print('한동안 저 방에 들어가는 건 꺼려질 것 같다. 밖을 더 돌아다녀 보자.')
    move_limit.lim3()
    floor.scount1 += 1 #이후로 볼 수 없음
